### ISSUE TITLE
Why do you invoke RevealHolizontalOrVerticalWins twice?

### ISSUE THREAD

**Issue by AlexKap23** [Selemabala/GameProgramTTT#24]
https://github.com/Selemabala/GameProgramTTT/blob/f9bdbe8fead3957a27073c864dbf87f57c6e67ef/GameProgramTTT/Program.cs#L51-L52

You invoke it without using the variable and then u invoke it again inside the if case. Why? Same thing applies to WiningStatusDiagnalValues method

The calculations are performed twice and this is not ideal of course.

**Comment by Selemabala** [comment]
I worked on this, however I have a problem needs help and I have a question.

Problem: Why does the choice statement come twice? is it because I have created a variable which takes the value of the method created? What is the good idea to avoid this problem. 

Question:  What is the general rule for using methods? Should methods be written directly or stored in a new created variable i.e should I create variables for all methods outputs?
